### ISSUE TITLE
Question: Integration with flow

### ISSUE THREAD

**Issue by amilajack** [miraks/babel-plugin-implicit-return#1]
Does this plugin integrate nicely with flow?

**Comment by miraks** [comment]
Never tried to use it with flow, so I don't know :) It depends on whether flow does type-checking before or after this plugin. I'll check it today or tomorrow.

**Comment by miraks** [comment]
Plugin seems to work with flow annotated files, but of course flow will complain about functions returning undefined. So you've to somehow run this plugin before running flow. As for now, flow doesn't provide options to run you own source code preprocessor before type-check. So answering your question I'd say that this plugin doesn't play nicely with flow. But I think it's possible to make them play well together with some clever hacks.
